steps:
  - name: "bash"
    id: "check-json"
    script: |
      apt-get update
      apt-get install jq -y
      for i in $(ls contents/); do echo contents/$i; cat contents/$i | jq empty; done
  - name: "gcr.io/cloud-builders/gcloud"
    id: "copy-json"
    waitFor: ["check-json"]
    args: ["gsutil", "cp", "-r", "contents/*", "gs://cloudbuild-sample-bbz/"]
