steps:
  - name: "gcr.io/cloud-builders/kubectl"
    id: "check-json"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        for i in $(ls contents/); do echo contents/$i; cat contents/$i | jq empty; done
  - name: "gcr.io/cloud-builders/gcloud"
    id: "copy-json"
    waitFor: ["check-json"]
    args: ["gsutil", "cp", "-r", "contents/*", "gs://cloudbuild-sample-bbz/"]
